# Code generated by AI (Claude Opus 5)
# stdout callback: one live progress line, changed tasks with their diff, failures, one-line recap

from ansible import context
from ansible.plugins.callback import CallbackBase

CLEAR = "\r\033[K"

class CallbackModule(CallbackBase):
    CALLBACK_VERSION = 2.0
    CALLBACK_TYPE = "stdout"
    CALLBACK_NAME = "chezmoi"

    def v2_playbook_on_play_start(self, play):
        mode = "check" if context.CLIARGS.get("check") else "apply"
        self._display.display("")
        self._display.display("▶ Ansible %s: %s" % (mode, play.get_name()), color="bright blue")

    def v2_playbook_on_task_start(self, task, is_conditional):
        self._display.display(CLEAR + task.get_name() + "...", newline=False)

    def v2_on_file_diff(self, result):
        # some modules (sysctl) report a diff that renders empty
        diff = self._get_diff(result._result.get("diff", {})).strip()
        if diff:
            self._display.display(CLEAR + diff)

    def v2_runner_on_ok(self, result):
        if result._result.get("changed"):
            self._display.display(CLEAR + "changed: " + result._task.get_name(), color="yellow")

    def v2_runner_on_failed(self, result, ignore_errors=False):
        self._display.display(CLEAR + "failed: " + result._task.get_name() + ": " + self._dump_results(result._result), color="red")

    def v2_playbook_on_stats(self, stats):
        for host in sorted(stats.processed):
            s = stats.summarize(host)
            color = "red" if s["failures"] or s["unreachable"] else "yellow" if s["changed"] else "green"
            self._display.display(
                CLEAR + "%s: ok=%d changed=%d failed=%d skipped=%d" % (host, s["ok"], s["changed"], s["failures"], s["skipped"]),
                color=color,
            )
