#!/bin/sh
# Code generated by AI (Claude Opus 5)

# use -K to exit on Ctrl+C
# use -e to exit the pager only on the second EOL scroll event (do not trigger Ansible check when reaching the end of the pager directly)
# force 'q' command to not run Ansible check (read and quit since nothing interesting to apply)
less -eK -+F --lesskey-content='#command;q quit 1' || { cat >/dev/null; exit 0; }

# hide additional scrolling or keys in pager (the weird ^A, ^OB, ^B, etc.)
stty -echo </dev/tty
trap 'stty echo </dev/tty' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

"$(dirname "$0")/play.sh" --check --diff
