#!/bin/sh
# Code generated by AI (Claude Opus 5)

export ANSIBLE_PYTHON_INTERPRETER=auto_silent ANSIBLE_STDOUT_CALLBACK=chezmoi

exec ansible-playbook -i localhost, -c local "$@" "$(dirname "$0")/../site.yml"
