[awareness]
level = "full"

[hooks]
exclude_commands = []
transparent_prefixes = [
    "mise exec --",
    "mise x --",
    "time",
    "timeout 10",
    "timeout 25",
    "timeout 30",
    "timeout 60",
    "timeout 120",
    "timeout 180",
    "timeout 200",
    "timeout 300",
    "timeout 500",
    "timeout 600",
]

[telemetry]
enabled = false
consent_given = false
consent_date = "2026-06-06T12:28:04.245511367+00:00"
