#!/bin/sh
# Code generated by AI (Claude Opus 5)

# shellcheck disable=SC1091
. "$(dirname "$0")/chezmoi-args.sh"
if [ -n "$CHEZMOI_TARGET" ] || [ -n "$CHEZMOI_EXCLUDE_SCRIPTS" ]; then
  exit 0
fi
[ -z "$CHEZMOI_DRY_RUN" ] || set -- --check "$@"

export ANSIBLE_PYTHON_INTERPRETER=auto_silent ANSIBLE_STDOUT_CALLBACK=chezmoi

exec ansible-playbook -i localhost, -c local "$@" "$(dirname "$0")/../ansible/site.yml"
