#!/bin/sh
# Code generated by AI (Claude Opus 5)
# read-source-state pre hook, runs on every chezmoi command so it must exit fast once done

set -e

env="$HOME/.local/state/chezmoi/env"
single="$HOME/.nix-profile/etc/profile.d/nix.sh"
multi=/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

# a pre-existing multi-user nix must not trigger the single-user installer
if [ ! -f "$single" ] && [ ! -f "$multi" ]; then
  curl -L https://nixos.org/nix/install | sh -s -- --no-daemon --no-modify-profile
fi

# shellcheck disable=SC1090
if [ -f "$single" ]; then . "$single"; else . "$multi"; fi

# tools the modify_ scripts need, a GC-rooted build independent from home.nix and its apply order
if [ ! -x "$env/bin/python3" ]; then
  mkdir -p "$(dirname "$env")"
  nix-build -E 'with import <nixpkgs> {}; buildEnv { name = "chezmoi-env"; paths = [ jq (python3.withPackages (ps: [ ps.tomlkit ])) ]; }' -o "$env"
fi

# home-manager init keeps an existing home.nix, otherwise its default one is overwritten in the file phase
if ! command -v home-manager >/dev/null 2>&1; then
  nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
  nix-channel --update
  nix-shell '<home-manager>' -A install
fi
