#!/bin/sh
# Code generated by AI (Claude Sonnet 5)

red='\033[0;31m'
yellow='\033[0;33m'
blue='\033[0;34m'
no_color='\033[0m'

error() {
  printf "${red}ERROR${no_color} %s\n" "$1" >&2
  return 1
}

warn() {
  printf "${yellow}WARN${no_color} %s\n" "$1"
}

info() {
  printf "${blue}INFO${no_color} %s\n" "$1"
}
