#!/bin/sh
# Code generated by AI (Claude Opus 5)

# shellcheck disable=SC1091
. "$(dirname "$0")/chezmoi-args.sh"

# chezmoi also pages 'apply -v' but never waits for the pager: scripts and the play run behind it, so stream it as a log
if [ "$CHEZMOI_COMMAND" != diff ]; then
  exec cat
fi

# a target diff and an excluded scripts diff need no check
if [ -n "$CHEZMOI_TARGET" ] || [ -n "$CHEZMOI_EXCLUDE_SCRIPTS" ]; then
  exec less -FRX
fi

out=$(mktemp)
trap 'stty echo </dev/tty; rm -f "$out"' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

# the check runs while the diff is reviewed, its output is replayed once the pager ends (colors kept for the replay)
ANSIBLE_FORCE_COLOR=1 "$(dirname "$0")/ansible.sh" --check --diff >"$out" 2>&1 &
pid=$!

# -e quits on the second EOF, 'q' (lesskey) and Ctrl+C (-K) cancel the check, the drain keeps chezmoi from EPIPE.
# TERM not INT: a background job of a non-interactive sh ignores INT. The check may already be done, hence the silenced kill.
less -eRK -+F --lesskey-content='#command;q quit 1' || { kill "$pid" 2>/dev/null; cat >/dev/null; exit 0; }

# hide keys typed while waiting for the check (the weird ^A, ^OB, ^B, etc.)
stty -echo </dev/tty
tail -n +1 -f --pid="$pid" "$out"
