# Code generated by AI (Claude Sonnet 5)

import json
import sys

def main():
    env = {}
    for line in sys.stdin:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition("=")
        env[key] = value

    env.update(json.loads(r'''{{ toJson .set }}'''))

    for key in sorted(env):
        sys.stdout.write(f"{key}={env[key]}\n")

if __name__ == "__main__":
    main()
