# Code generated by AI (Claude Opus 5)

import itertools
import json
import sys

def merge(table, wanted):
    for key, value in wanted.items():
        if isinstance(value, dict) and isinstance(table.get(key), dict):
            merge(table[key], value)
        elif isinstance(value, list) and isinstance(table.get(key), list):
            table[key].extend(item for item in value if item not in table[key])
        else:
            table[key] = value

def main():
    # retrieve each input file lines to be able to filter unwanted ones during parsing (i.e. comments)
    lines = sys.stdin.read().splitlines(keepends=True)

    # ignore comment lines from parsing (JSONC)
    head = list(itertools.takewhile(lambda line: line.startswith("//"), lines))

    text = "".join(lines[len(head):])
    doc = json.loads(text) if text.strip() else {}
    merge(doc, json.loads(r'''{{ toJson .set }}'''))

    # sort merged list values in place, e.g. permission arrays
    for path in json.loads(r'''{{ toJson (.sort | default list) }}'''):
        *parents, key = path
        table = doc
        for parent in parents:
            table = table[parent]
        # append a sentinel above every char so a string sorts after any longer string it prefixes
        table[key].sort(key=lambda item: str(item).lower() + "￿")

    sys.stdout.write("".join(head))
    json.dump(doc, sys.stdout, indent={{ .indent }}, ensure_ascii=False)
    sys.stdout.write("\n")

if __name__ == "__main__":
    main()
