# Code generated by AI (Claude Opus 5)

import itertools
import json
import sys

from functools import reduce

def merge(table, wanted):
    for key, value in wanted.items():
        if isinstance(value, dict) and isinstance(table.get(key), dict):
            merge(table[key], value)
        elif isinstance(value, list) and isinstance(table.get(key), list):
            table[key].extend(item for item in value if item not in table[key])
        else:
            table[key] = value

def main():
    # retrieve each input file lines to be able to filter unwanted ones during parsing (i.e. comments)
    lines = sys.stdin.read().splitlines(keepends=True)

    # ignore comment lines from parsing (JSONC)
    head = list(itertools.takewhile(lambda line: line.startswith("//"), lines))

    text = "".join(lines[len(head):])
    doc = json.loads(text) if text.strip() else {}
    wanted = json.loads(r'''{{ toJson .set }}''')

    # assign overridden paths in place, delete+reinsert would move the key to the dict's end
    for path in json.loads(r'''{{ toJson (.override | default list) }}'''):
        *parents, key = path
        src = reduce(lambda d, k: d[k], parents, wanted)
        dst = reduce(lambda d, k: d.setdefault(k, {}), parents, doc)
        dst[key] = src[key]
        del src[key]

    merge(doc, wanted)

    # sort merged list values or dict keys in place; the sentinel sorts a string after any longer string it prefixes
    sort_key = lambda item: str(item).lower() + "￿"
    for path in json.loads(r'''{{ toJson (.sort | default list) }}'''):
        *parents, key = path
        table = doc
        for parent in parents:
            table = table[parent]
        if isinstance(table[key], dict):
            table[key] = {k: table[key][k] for k in sorted(table[key], key=sort_key)}
        else:
            table[key].sort(key=sort_key)

    sys.stdout.write("".join(head))
    json.dump(doc, sys.stdout, indent={{ .indent }}, ensure_ascii=False)
    sys.stdout.write("\n")

if __name__ == "__main__":
    main()
