# Code generated by AI (Claude Opus 5)

import json
import sys

import tomlkit

def merge(table, wanted):
    for key, value in wanted.items():
        if isinstance(value, dict) and isinstance(table.get(key), dict):
            merge(table[key], value)
        else:
            table[key] = value

def main():
    doc = tomlkit.parse(sys.stdin.read())
    merge(doc, json.loads(r'''{{ toJson .set }}'''))

    # remove unwanted keys from TOML file
    for *parents, key in json.loads(r'''{{ toJson .unset }}'''):
        table = doc
        for parent in parents:
            table = table.get(parent, {})
        table.pop(key, None)

    # re-append keys in order, tomlkit has no sort
    for path in json.loads(r'''{{ toJson .sort }}'''):
        table = doc
        for part in path:
            table = table.get(part, {})
        for key in sorted(table):
            table[key] = table.pop(key)

    sys.stdout.write(tomlkit.dumps(doc))

if __name__ == "__main__":
    main()
