[tools]
gh = "latest"
glab = { version = "latest", exe = "glab" }
go = "latest"
hugo-extended = "latest"
opentofu = "latest"
usage = "latest"
sops = "latest"
tflint = "latest"
golangci-lint = "latest"
"github:sass/dart-sass" = "latest"
bun = "latest"
cosign = "latest"
pre-commit = "latest"
node = "latest"
claude = "latest"
terraform = "latest"
copilot = "latest"
pnpm = "latest"
rtk = "latest"
shellcheck = "latest"
